from psycopg2 import connect
from flask import session
import os

# PostgreSQL configuration
DB_HOST = os.getenv("DB_HOST", "dpg-dabua6fqj5pc739c034g-a")
DB_PORT = os.getenv("DB_PORT", "5432")
DB_NAME = os.getenv("DB_NAME", "eventpass_5x1a")
DB_USER = os.getenv("DB_USER", "root")
DB_PASSWORD = os.getenv("DB_PASSWORD", "8SmTeqShZSbeU6nMrkYPBLuwzJcKgDb9")


class Admin:

    def connection(self):
        con = connect(
            host=DB_HOST,
            port=DB_PORT,
            user=DB_USER,
            password=DB_PASSWORD,
            dbname=DB_NAME
        )
        return con

    def adminInsert(self, college, email, password):

        db = self.connection()
        cur = db.cursor()

        sq = '''
            CREATE TABLE IF NOT EXISTS admin(
                college VARCHAR(255),
                email VARCHAR(255) PRIMARY KEY,
                password VARCHAR(255)
            )
        '''

        cur.execute(sq)

        # Check duplicate
        cur.execute(
            "SELECT 1 FROM admin WHERE email=%s",
            (email,)
        )

        exist = cur.fetchone()

        if exist:
            db.close()
            return 1

        sq = '''
            INSERT INTO admin(college, email, password)
            VALUES(%s, %s, %s)
        '''

        record = [college, email, password]

        cur.execute(sq, record)

        db.commit()
        db.close()

        return 0

    def adminLogin(self, email, password):

        db = self.connection()
        cur = db.cursor()

        sq = '''
            SELECT college, email
            FROM admin
            WHERE email=%s AND password=%s
        '''

        value = [email, password]

        cur.execute(sq, value)

        row = cur.fetchall()

        db.close()

        if row:
            session["adminCollege"] = row[0][0]
            session["adminEmail"] = row[0][1]

            return True

        else:
            return False

    def adProfile(self):

        db = self.connection()
        cur = db.cursor()

        sq = '''
            SELECT college, email
            FROM admin
            WHERE email=%s
        '''

        value = [session['adminEmail']]

        cur.execute(sq, value)

        row = cur.fetchall()

        db.close()

        return row

    def adminProfileUpdate(self, college):

        db = self.connection()
        cur = db.cursor()

        # Fixed SQL syntax
        sq = '''
            UPDATE admin
            SET college=%s
            WHERE email=%s
        '''

        value = [
            college,
            session['adminEmail']
        ]

        cur.execute(sq, value)

        db.commit()

        session['adminCollege'] = college

        db.close()

    def addEvent(
        self,
        eventName,
        startDate,
        endDate,
        venue,
        capacity,
        type
    ):
        db = self.connection()
        cur = db.cursor()
        sq = '''
            CREATE TABLE IF NOT EXISTS event(
                eventID INTEGER
                    GENERATED BY DEFAULT AS IDENTITY
                    (START WITH 101),
                adminEmail VARCHAR(255),
                eventName VARCHAR(255),
                startDate DATE,
                endDate DATE,
                venue VARCHAR(255),
                capacity INTEGER,
                type VARCHAR(255),
                PRIMARY KEY(eventID)
            )
        '''
        cur.execute(sq)
        sq = '''
            INSERT INTO event(
                adminEmail,
                eventName,
                startDate,
                endDate,
                venue,
                capacity,
                type
            )
            VALUES(%s, %s, %s, %s, %s, %s, %s)
        '''
        record = [
            session['adminEmail'],
            eventName,
            startDate,
            endDate,
            venue,
            capacity,
            type
        ]
        cur.execute(sq, record)
        db.commit()
        db.close()

    def manageEvent(self):
        db = self.connection()
        cur = db.cursor()
        sq = '''
            SELECT
                eventID,
                eventName,
                startDate,
                endDate,
                venue,
                capacity,
                type
            FROM event
            WHERE adminEmail=%s
        '''
        value = [session['adminEmail']]
        cur.execute(sq, value)
        row = cur.fetchall()
        db.close()
        return row

    def deleteEvent(self, eventID):
        db = self.connection()
        cur = db.cursor()
        sq = '''
            DELETE FROM event
            WHERE eventID=%s
        '''
        record = [eventID]
        cur.execute(sq, record)
        db.commit()
        db.close()

    def viewEvent(self, eventID):
        db = self.connection()
        cur = db.cursor()
        sq = '''
            SELECT
                eventID,
                eventName,
                startDate,
                endDate,
                venue,
                capacity,
                type
            FROM event
            WHERE eventID=%s
                '''
        value = [eventID]
        cur.execute(sq, value)
        row = cur.fetchall()
        db.close()
        return row

    def updateEvent(self,eventID,eventName,startDate,endDate,venue,capacity,type):
        db = self.connection()
        cur = db.cursor()
        sq = '''
            UPDATE event
            SET
                eventName=%s,
                startDate=%s,
                endDate=%s,
                venue=%s,
                capacity=%s,
                type=%s
            WHERE eventID=%s
        '''
        record = [
            eventName,
            startDate,
            endDate,
            venue,
            capacity,
            type,
            eventID
        ]
        cur.execute(sq, record)
        db.commit()
        db.close()

    def viewUsers(self, eventID):
        db = self.connection()
        cur = db.cursor()
        sq = '''
            SELECT
                e.eventID,
                u.firstName,
                u.lastName
            FROM eventpass e
            JOIN users u
                ON e.email = u.email
            WHERE e.eventID=%s
        '''
        value = [eventID]
        cur.execute(sq, value)
        row = cur.fetchall()
        db.close()
        return row

    def passCount(self, eventID):
        db = self.connection()
        cur = db.cursor()
        sq = '''
            SELECT COUNT(eventID)
            FROM eventpass
            WHERE eventID=%s
        '''
        value = [eventID]
        cur.execute(sq, value)
        row = cur.fetchall()
        db.close()
        return row